name: domora
description: "Domora - Plataforma de servicios para el hogar."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

  # Supabase
  supabase_flutter: ^2.5.6

  # State management
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5

  # Navigation
  go_router: ^14.2.0

  # Storage
  flutter_secure_storage: ^9.2.2

  # Media
  image_picker: ^1.1.2

  # Utils
  intl: 0.20.2
  flutter_localizations:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  dartz: ^0.10.1
  http: ^1.1.0

  # Tipografía
  google_fonts: ^6.2.1
  flutter_map: ^8.3.0
  latlong2: ^0.9.1
  geolocator: ^12.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/welcome/
