// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxqndpE3GrN6da94_q2kNFaZolSydDUoc',
    appId: '1:798851561105:web:9ba532c7d8fed6fe357130',
    messagingSenderId: '798851561105',
    projectId: 'domora-9b1a8',
    authDomain: 'domora-9b1a8.firebaseapp.com',
    storageBucket: 'domora-9b1a8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDm90yLFOvdp1ByUDgyMw-CFZQkVKvk30U',
    appId: '1:798851561105:android:7e1a543a07e241ca357130',
    messagingSenderId: '798851561105',
    projectId: 'domora-9b1a8',
    storageBucket: 'domora-9b1a8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrwlol0q6vY-NGtv19prANLZF2oBy1xLQ',
    appId: '1:798851561105:ios:62296dd6574d0e41357130',
    messagingSenderId: '798851561105',
    projectId: 'domora-9b1a8',
    storageBucket: 'domora-9b1a8.firebasestorage.app',
    iosBundleId: 'com.domora.domora',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrwlol0q6vY-NGtv19prANLZF2oBy1xLQ',
    appId: '1:798851561105:ios:62296dd6574d0e41357130',
    messagingSenderId: '798851561105',
    projectId: 'domora-9b1a8',
    storageBucket: 'domora-9b1a8.firebasestorage.app',
    iosBundleId: 'com.domora.domora',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxqndpE3GrN6da94_q2kNFaZolSydDUoc',
    appId: '1:798851561105:web:d46afa19a59f57fd357130',
    messagingSenderId: '798851561105',
    projectId: 'domora-9b1a8',
    authDomain: 'domora-9b1a8.firebaseapp.com',
    storageBucket: 'domora-9b1a8.firebasestorage.app',
  );
}
